Payment:
  extensions:
    - LoyaltyVoucherPayment
Member:
  extensions:
    - LoyaltyVoucherMemberExtension
Order:
  extensions:
    - LoyaltyVoucherOrderExtension
SiteConfig:
  extensions:
    - LoyaltyVoucherConfig